import type { Metadata } from 'next'
import localFont from 'next/font/local'

import './globals.css'
import { UserProvider } from '@auth0/nextjs-auth0/client';

// Font files can be colocated inside of `pages`
const myFont = localFont({ src: '../colfax-font/Colfax-Regular.woff2' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={myFont.className}>{children}</body>
      </UserProvider>
    </html>
  )
}
